name: Python Tests

on:
  push:
    branches:
      - "main"
    paths:
      - "**/*.py"
      - "**/pyproject.toml"
      - '.github/workflows/pytest.yml'
  pull_request:
    branches:
      - "main"
    paths:
      - "**/*.py"
      - "**/pyproject.toml"
      - '.github/workflows/pytest.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.11"

    concurrency:
      group: ci-task-lock
      cancel-in-progress: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
          github-token: ${{ github.token }}

      - name: Install dependencies
        working-directory: ./src_py
        run: |
          uv venv
          uv pip install -e .[dev]

      - name: Run linter
        working-directory: ./src_py
        run: |
          make lint

      - name: Run tests
        working-directory: ./src_py
        run: |
          uv run pytest -vvv tests
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GLM_API_KEY: ${{ secrets.GLM_API_KEY }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          SILICONFLOW_API_KEY: ${{ secrets.SILICONFLOW_API_KEY }}
